apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: viken-no

resources:
  - ../../../base
  - onepassword.yaml

patches:
  
  - target:
      kind: Deployment
      name: adapter-sikri-arkiv
    path: deployment.yaml
