springfox:
  title: 'FINT SSE Adapter Skeleton'
  version: '@version@'

fint:
  adapter:
    endpoints:
      sse: /sse/%s
      status: /status
      response: /response

  oauth:
    enabled: true
    username: ${fint.core.oauth2.username}
    password: ${fint.core.oauth2.password}
    client-id: ${fint.core.oauth2.client-id}
    client-secret: ${fint.core.oauth2.client-secret}
#    access-token-uri:
#    scope:

security:
  basic:
    enabled: false

management:
  security:
    enabled: false

endpoints:
  enabled: false
  health:
    enabled: true
  prometheus:
    enabled: true
  metrics:
    enabled: true
