server:
  port: 8091

springfox:
  title: 'FINT SSE Adapter Skeleton'
  version: '@version@'

fint:
  sikri:
    defaults:
      casetype:
        tilskudd-fartoy:
          klassifikasjon:
          administrativEnhet:
          arkivdel:
          noekkelord:
          saksstatus: B
          korrespondansepartType:
          journalpostType:
          journalstatus:
          dokumentstatus:
          dokumentType:
          tilknyttetRegistreringSom:
        personalmappe:
          arkivdel: PERS
          saksstatus: B
          saksmappeType: P
          ufordeltAdministrativEnhet: 29
          ufordeltSaksbehandler: 0
          tilgangskode: P
          journalenhet: VFRÅD
          saksStatusAvsluttetId: A

    customAttributes:
      casetype:
        tilskudd-fartoy:
          kallesignal: customAttribute1
          fartoynavn: customAttribute2
          soknadsnummer: customAttribute3
          kulturminneid: customAttribute4

  adapter:
    endpoints:
      sse: /sse/%s
      status: /status
      response: /response
      providers:
        arkiv: https://beta.felleskomponent.no/administrasjon/arkiv/provider
        personal: https://alpha.felleskomponent.no/administrasjon/personal/provider
        kulturminne: https://beta.felleskomponent.no/kultur/kulturminnevern/provider
    organizations: viken.no

  oauth:
    enabled: true
  #    username:
  #    password:
  #    client-id:
  #    client-secret:
  #    access-token-uri:
  #    scope:

security:
  basic:
    enabled: false
