server:
  port: 8091
  servlet-path: /actuator

springfox:
  title: 'FINT SSE Adapter Skeleton'
  version: '@version@'

fint:
  adapter:
    endpoints:
      sse: /sse/%s
      status: /status
      response: /response

  oauth:
    enabled: true
  #    username:
  #    password:
  #    client-id:
  #    client-secret:
  #    access-token-uri:
  #    scope:

security:
  basic:
    enabled: false

management:
  security:
    enabled: false

endpoints:
  enabled: false
  health:
    enabled: true
  prometheus:
    enabled: true
  metrics:
    enabled: true
