server:
  port: 8091

springfox:
  title: 'FINT SSE Adapter Skeleton'
  version: '@version@'

fint:
  sikri:
    defaults:
      casetype:
        tilskudd-fartoy:
          klassifikasjon: Fartøy
          administrativEnhet: 9
          arkivdel: RFK
          noekkelord:
          saksstatus: B
          korrespondansepartType: 5
          journalpostType: 110
          journalstatus: 3
          dokumentstatus: 1
          dokumentType: 1
          tilknyttetRegistreringSom: 1
    customAttributes:
      casetype:
        tilskudd-fartoy:
          kallesignal: customAttribute1
          fartoynavn: customAttribute2
          soknadsnummer: customAttribute3
          kulturminneid: customAttribute4

  adapter:
    endpoints:
      sse: /sse/%s
      status: /status
      response: /response
      providers:
        arkiv: https://beta.felleskomponent.no/administrasjon/arkiv/provider
        personal: https://alpha.felleskomponent.no/administrasjon/personal/provider
        kulturminne: https://beta.felleskomponent.no/kultur/kulturminnevern/provider
    organizations: a.arkitektum.no

  oauth:
    enabled: true
  #    username:
  #    password:
  #    client-id:
  #    client-secret:
  #    access-token-uri:
  #    scope:

security:
  basic:
    enabled: false
