apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vlfk-no

resources:
  - ../../../base
  - onepassword.yaml

commonLabels:
  app.kubernetes.io/instance: adapter-arkiv-sikri_vlfk-no
  fintlabs.no/org-id: vlfk.no

patches:
  
  - target:
      kind: Deployment
      name: adapter-arkiv-sikri
    path: deployment.yaml

