apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: innlandetfylke-no

resources:
  - ../../../base
  - onepassword.yaml

commonLabels:
  app.kubernetes.io/instance: adapter-sikri-arkiv_innlandetfylke-no
  fintlabs.no/org-id: innlandetfylke.no

patches:
  
  - target:
      kind: Deployment
      name: adapter-sikri-arkiv
    path: deployment.yaml
