apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base
  - onepassword.yaml

patches:
  
  - target:
      kind: Deployment
      name: adapter-sikri-arkiv
    path: deployment.yaml

  - target:
      kind: Deployment
      name: adapter-sikri-arkiv
    patch: |-
      - op: replace
        path: "/metadata/name"
        value: "adapter-sikri-arkiv-mrfylke-no"
      - op: replace
        path: "/spec/selector/matchLabels/app"
        value: "adapter-sikri-arkiv-mrfylke-no"
      - op: replace
        path: "/spec/template/metadata/labels/app"
        value: "adapter-sikri-arkiv-mrfylke-no"
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: "adapter-sikri-arkiv-mrfylke-no"
    
# remove fint.case.coding.format.* from base 🫣
  - target:
      kind: Deployment
      name: adapter-sikri-arkiv
    patch: |-
      - op: remove
        path: "/spec/template/spec/containers/0/env/89"
      - op: remove
        path: "/spec/template/spec/containers/0/env/88"
      - op: remove
        path: "/spec/template/spec/containers/0/env/87"
      - op: remove
        path: "/spec/template/spec/containers/0/env/86"