apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: viken-no

resources:
  - ../../../base
  - onepassword.yaml
  - fint-adapter.yaml

commonLabels:
  app.kubernetes.io/instance: adapter-sikri-arkiv_fylkesting-viken-no
  fintlabs.no/org-id: fylkesting.viken.no

patches:
  
  - target:
      kind: Deployment
      name: adapter-sikri-arkiv
    path: deployment.yaml

  - target:
      kind: Deployment
      name: adapter-sikri-arkiv
    patch: |-
      - op: replace
        path: "/metadata/name"
        value: "adapter-sikri-arkiv-fylkesting-viken-no"
      - op: replace
        path: "/spec/selector/matchLabels/app"
        value: "adapter-sikri-arkiv-fylkesting-viken-no"
      - op: replace
        path: "/spec/template/metadata/labels/app"
        value: "adapter-sikri-arkiv-fylkesting-viken-no"
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: "adapter-sikri-arkiv-fylkesting-viken-no"
