apiVersion: fintlabs.no/v1alpha1
kind: FintAdapter
metadata:
  name: sikri-arkiv-api
  namespace: afk-no
  labels:
    app.kubernetes.io/name: sikri-arkiv-api
    app.kubernetes.io/instance: sikri-arkiv-api_afk-no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: sikri-arkiv-adapter
    app.kubernetes.io/part-of: arkiv
    fintlabs.no/team: arkiv
    fintlabs.no/org-id: afk.no

spec:
  orgId: afk.no
  note: Brukes av sikri-arkiv-adapter. Automatisk opprettet ved oppretting av adapter.
  components:
    - arkiv_kodeverk
    - arkiv_noark
    - arkiv_kulturminnevern
    - arkiv_samferdsel
    - arkiv_personal