apiVersion: apps/v1
kind: Deployment
metadata:
  name: adapter-sikri-arkiv
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: adapter-sikri-arkiv
  template:
    metadata:
      labels:
        app: adapter-sikri-arkiv
      annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "8080"
          prometheus.io/path: "prometheus"
    spec:
      restartPolicy: Always
      volumes:
        - name: tempdir
          emptyDir: 
            sizeLimit: 1G
      containers:
        - name: adapter-sikri-arkiv
          image: ghcr.io/fintlabs/fint-sikri-arkiv-adapter:empty
          resources:
            limits:
              memory: "2Gi"
              cpu: "2"
            requests:
              memory: "1Gi"
              cpu: "250m"
          ports:
            - containerPort: 8091
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - name: tempdir
              mountPath: /temp
          env:
            - {name: TZ, value: Europe/Oslo}
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -Xmx1G -verbose:gc
                -XX:+ExitOnOutOfMemoryError
                -Dfile.encoding=UTF-8
                -Dcom.sun.security.enableAIAcaIssuers=true
                -Dcom.sun.xml.ws.transport.http.client.HttpTransportPipe.dump=true
                -Dcom.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.dump=true
                -Dcom.sun.xml.ws.transport.http.HttpAdapter.dump=true
                -Dcom.sun.xml.internal.ws.transport.http.HttpAdapter.dump=true
                -Dcom.sun.xml.internal.ws.transport.http.HttpAdapter.dumpTreshold=15000
            - {name: security.basic.enabled, value: "false"}
            - {name: endpoints.enabled, value: "false"}
            - {name: endpoints.sensitive, value: "false"}
            - {name: endpoints.health.enabled, value: "true" }
            - {name: endpoints.prometheus.enabled, value: "true" }
            - {name: endpoints.metrics.enabled, value: "true" }
            - {name: fint.adapter.reject-unknown-events, value: 'false'}
            - {name: fint.file-cache.directory, value: '/temp'}
            - {name: fint.sikri.wsdl-location, value: /app }
            - {name: logging.level.no.fint.arkiv, value: trace}
            - {name: logging.level.no.fint.sikri, value: trace}