apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bfk-no

resources:
  - ../../../base
  - onepassword.yaml
  - fint-adapter.yaml

commonLabels:
  app.kubernetes.io/instance: adapter-arkiv-sikri_bfk-no
  fintlabs.no/org-id: bfk.no

patches:
  
  - target:
      kind: Deployment
      name: adapter-arkiv-sikri
    path: deployment.yaml
