apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: afk-no

resources:
  - ../../../base
  - onepassword.yaml
#  - fint-adapter.yaml

commonLabels:
  app.kubernetes.io/instance: adapter-arkiv-sikri_fylkesting-afk-no
  fintlabs.no/org-id: fylkesting.afk.no

patches:
  
  - target:
      kind: Deployment
      name: adapter-arkiv-sikri
    path: deployment.yaml

  - target:
      kind: Deployment
      name: adapter-arkiv-sikri
    patch: |-
      - op: replace
        path: "/metadata/name"
        value: "adapter-arkiv-sikri-fylkesting-afk-no"
      - op: replace
        path: "/spec/selector/matchLabels/app"
        value: "adapter-arkiv-sikri-fylkesting-afk-no"
      - op: replace
        path: "/spec/template/metadata/labels/app"
        value: "adapter-arkiv-sikri-fylkesting-afk-no"
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: "adapter-arkiv-sikri-fylkesting-afk-no"
