apiVersion: apps/v1
kind: Deployment
metadata:
  name: adapter-sikri-arkiv
  namespace: fridiks-no
spec:
  template:
    spec:
      containers:
        - name: adapter-sikri-arkiv
          envFrom:
            - secretRef:
                name: arkiv-sikri-fridiks-no
            - secretRef:
                name: sikri-arkiv-beta # fint-adapter
          env:
            - {name: fint.case.coding.format.RA-PDF, value: 'PDF'}
            - {name: fint.case.coding.format.RA-TEKST, value: 'TEXT'}
            - {name: fint.case.coding.format.RA-JPEG, value: 'JPEG'}
            - {name: fint.case.coding.format.RA-TIFF6, value: 'TIFF'}
            - {name: springfox.title, value: "Elements Adapter for FRID IKS"}
            - {name: fint.case.defaults.personalmappe.arkivdel, value: 'PERS'}
            - {name: fint.case.defaults.personalmappe.saksstatus, value: 'B'}
            - {name: fint.case.defaults.personalmappe.saksmappeType, value: 'PE'}
            - {name: fint.case.defaults.personalmappe.administrativEnhet, value: '28'}
            - {name: fint.case.defaults.personalmappe.saksbehandler, value: '0'}
            - {name: fint.case.defaults.personalmappe.tilgangskode, value: 'P'}
            - {name: fint.case.defaults.personalmappe.journalenhet, value: 'N/A'}
            - {name: fint.case.defaults.personalmappe.saksStatusAvsluttetId, value: 'A'}
            - {name: fint.case.defaults.sak.journalenhet, value: 'N/A'}
            - {name: fint.case.defaults.sak.dokumentType, value: ND }
            - {name: fint.sikri.identity.casetype.default, value: flyt }
            - {name: fint.sikri.identity.casetype.sak, value: flyt }
            - {name: fint.sikri.identity.casetype.personalmappe, value: personal}
            - {name: fint.adapter.endpoints.providers.kodeverk, value: https://beta.felleskomponent.no/arkiv/kodeverk/provider}
            - {name: fint.adapter.endpoints.providers.noark, value: https://beta.felleskomponent.no/arkiv/noark/provider}
            - {name: fint.adapter.endpoints.providers.personal, value: https://beta.felleskomponent.no/arkiv/personal/provider}
